version: "3"

services:
  db:
    image: mysql:8.3.0
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
      - type: bind
        source: ./db/conf.d
        target: /etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: sample
    ports:
      - "3306:3306"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend/app:/src/app
    ports:
      - "8080:8080"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    tty: true
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend/app
        target: /app

volumes:
  db-store: