version: "3"

services:
  db:
    image: mysql:8.3.0
    volumes:
      - type: volume
        source: db-store
        target: /var/lib/mysql
      - type: bind
        source: ./db/conf.d
        target: /etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: sample
    ports:
      - "3306:3306"

volumes:
  db-store: