# Generated by Django 4.2.10 on 2024-02-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', help_text='やること', max_length=200)),
                ('state', models.IntegerField(choices=[(1, 'Ready'), (2, 'Doing'), (3, 'Done')], default=1)),
                ('due_at', models.DateField(help_text='いつやるのか')),
                ('created_at', models.DateField(auto_now_add=True, help_text='作成日')),
                ('updated_at', models.DateField(auto_now=True, help_text='更新日')),
            ],
        ),
    ]
